name: '🐛 Report a bug'
description: 'Is something not working as you expect?'
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!

        Before posting, please check that the bug hasn't already been:
        * fixed in the next release (https://github.com/stylelint/stylelint/blob/main/CHANGELOG.md)
        * discussed previously (https://github.com/stylelint/stylelint/search)

        You can help us fix the bug more quickly by:
        1. Figuring out what needs doing and proposing it.
        2. Writing the code and submitting a PR once the bug is confirmed.
  - type: textarea
    id: reproduce-bug
    attributes:
      label: 'What steps are needed to reproduce the bug?'
    validations:
      required: true
  - type: input
    id: stylelint-rule
    attributes:
      label: 'Which rule, if any, is the bug related to?'
      placeholder: 'e.g. `number-leading-zero`'
    validations:
      required: false
  - type: textarea
    id: stylelint-configuration
    attributes:
      label: 'What Stylelint configuration is needed to reproduce the bug?'
      description: 'Provide the smallest reproducible example.'
      placeholder: |
        e.g.

        ```json
        {
          "rules": {
            "number-leading-zero": "always"
          }
        }
        ```
    validations:
      required: false
  - type: input
    id: stylelint-version
    attributes:
      label: 'Which version of Stylelint are you using?'
      placeholder: 'e.g. `14.0.0`'
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What did you expect to happen?'
      placeholder: |
        e.g. "No warnings to be flagged."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 'What actually happened?'
      description: 'For example, what warnings or errors did you get?'
      placeholder: |
        e.g. "The following warnings were flagged:"

        ```
        test.css
        2:4    Expected a leading zero (number-leading-zero)
        ```
    validations:
      required: true
  - type: input
    id: non-standard-syntax
    attributes:
      label: 'Does the bug relate to non-standard syntax?'
      description: 'For example, a construct from SCSS, Less or CSS-in-JS.'
      placeholder: |
        e.g. "Yes, it's related to SCSS nested properties."
    validations:
      required: false
